// list of items
export const items = [
  {
    itemName: "Flip machine",
    price: 15000,
    earning: 25,
    maxPurchase: 500,
    type: "ability",
    unit: "click",
    itemImg: "img/grill.png",
    itemCount: 0,
    index: 0,
  },
  {
    itemName: "ETF Stock",
    price: 300000,
    earning: 0.1,
    maxPurchase: Infinity,
    type: "investment",
    unit: "sec",
    itemImg: "img/chart.png",
    itemCount: 0,
    index: 1,
  },
  {
    itemName: "ETF Bonds",
    price: 300000,
    earning: 0.07,
    maxPurchase: Infinity,
    type: "investment",
    unit: "sec",
    itemImg: "img/chart.png",
    itemCount: 0,
    index: 2,
  },
  {
    itemName: "Lemonade Stand",
    price: 30000,
    earning: 30,
    maxPurchase: 1000,
    type: "real estate",
    unit: "sec",
    itemImg: "img/juice.png",
    itemCount: 0,
    index: 3,
  },
  {
    itemName: "Ice Cream Truck",
    price: 100000,
    earning: 120,
    maxPurchase: 500,
    type: "real estate",
    unit: "sec",
    itemImg: "img/ice-cream.png",
    itemCount: 0,
    index: 4,
  },
  {
    itemName: "House",
    price: 20000000,
    earning: 32000,
    maxPurchase: 100,
    type: "real estate",
    unit: "sec",
    itemImg: "img/home.png",
    itemCount: 0,
    index: 5,
  },
  {
    itemName: "Town House",
    price: 40000000,
    earning: 64000,
    maxPurchase: 100,
    type: "real estate",
    unit: "sec",
    itemImg: "img/modern-house.png",
    itemCount: 0,
    index: 6,
  },
  {
    itemName: "Mansion",
    price: 250000000,
    earning: 500000,
    maxPurchase: 20,
    type: "real estate",
    unit: "sec",
    itemImg: "img/condominium.png",
    itemCount: 0,
    index: 7,
  },
  {
    itemName: "Industrial Space",
    price: 1000000000,
    earning: 2200000,
    maxPurchase: 10,
    type: "real estate",
    unit: "sec",
    itemImg: "img/factory.png",
    itemCount: 0,
    index: 8,
  },
  {
    itemName: "Hotel Skyscraper",
    price: 10000000000,
    earning: 25000000,
    maxPurchase: 5,
    type: "real estate",
    unit: "sec",
    itemImg: "img/skyscrapers.png",
    itemCount: 0,
    index: 9,
  },
  {
    itemName: "Bullet-Speed Sky Railway",
    price: 10000000000000,
    earning: 30000000000,
    maxPurchase: 1,
    type: "real estate",
    unit: "sec",
    itemImg: "img/train.png",
    itemCount: 0,
    index: 10,
  },
];
